### ISSUE TITLE
Inkscape is barely usable with Pop Icons (and theme)

### ISSUE THREAD

**Issue by kpuljek** [system76/pop-icon-theme#10]
**Reporter info**

 * Distribution - (run ```lsb_release -a```)

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)

libgtk-3-0:
  Installed: 3.18.9-1ubuntu3.3
  Candidate: 3.18.9-1ubuntu3.3
  Version table:
 *** 3.18.9-1ubuntu3.3 500
        500 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.18.9-1ubuntu3 500
        500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages

 * Desktop environment - 

Unity

**Is this issue an Icon Request?**

Nope!

**Pop version (if you knew)**

Icons 1.1.4
GTK 1.3.1.2

**Related Application and/or Shell theming (or name of widget)**

Inkscape

**Actual issue**

When using Pop themes, Inkscape doesn't allow using my own custom icons (which work under other themes) and themes with Pop icons, which would be okay if they weren't so small and barely visible (especially if active - I'll attach some screenshots). They should either be bigger, or darker for better contrast. Or perhaps the theme could be tweaked so that it allows custom theming (Inkscape usually picks up icons from /home/.inkscape/icons, but it doesn't while using Pop, can't say why.)

**Steps to reproduce (if you knew)**

Apply Pop icons, start Inkscape

**Expected behaviour**

I expect to see the interface well!

**Behaviour in Adwaita**

Can't say. Probably the same.

![screenshot from 2017-06-09 14-44-48](https://user-images.githubusercontent.com/9851336/26975950-3a82c5c0-4d22-11e7-8994-f47bbb2888f1.png)
![screenshot from 2017-06-09 14-44-57](https://user-images.githubusercontent.com/9851336/26975951-3a85fa9c-4d22-11e7-9b00-f37c821f5bfa.png)

**Comment by isantop** [comment]
This is caused by poor software design in upstream Inkscape, and is due to the fact that they don't either specify a symbolic icon color palate, and use toolbars classes that specify dark icons instead of light ones. As a work around for this issue I've made recolored versions of the non-symbolic icons which should help improve readability, but this is a bug that should be filed against Inkscape to help them bring the GUI in line with modern GTK applications.
