### ISSUE TITLE
Numbers appear to render in different sizes

### ISSUE THREAD

**Issue by skulkingfox** [system76/pop-icon-theme#17]
**Reporter info**

**Related Application and/or Shell theming (or name of widget)**

Occurs across applications (Chrome, Settings, etc)

**Actual issue**

Font size appears mismatched in certain situations. 

![screenshot from 2017-10-02 13-32-30](https://user-images.githubusercontent.com/8932534/31098032-331a77d4-a776-11e7-8a82-d706880b1f71.png)
![screenshot from 2017-10-02 13-30-09](https://user-images.githubusercontent.com/8932534/31098030-3304788a-a776-11e7-80aa-281c472f5b73.png)
![screenshot from 2017-10-02 13-29-45](https://user-images.githubusercontent.com/8932534/31098031-331761d4-a776-11e7-8212-7d24bd0e65cb.png)

**Comment by isantop** [comment]
This is actually a feature of some fonts, including Fira, where some letters use ascenders and others use decenders. https://en.wikipedia.org/wiki/Text_figures
