### ISSUE TITLE
[Icon Request] GNOME Contacts

### ISSUE THREAD

**Issue by ryanleesipes** [system76/pop-icon-theme#2]
The GNOME contacts app does not look right in the Pop icon theme.

The default (which looks like an old address book), was better than the two heads with the transparent layer behind them.

![gnome_contacts](https://cloud.githubusercontent.com/assets/2141621/25911495/4bbc6ecc-3571-11e7-8185-d280d409aaac.png)

**Comment by isantop** [comment]
Fixed with upstream Papirus.
