### ISSUE TITLE
Icon Request  Lazarus (1.6.4) and Modem Manager GUI

### ISSUE THREAD

**Issue by go-jdiego** [system76/pop-icon-theme#3]
The default icons are displayed, no icons have been created for these applications
![captura de pantalla de 2017-05-10 12-05-26](https://cloud.githubusercontent.com/assets/28605562/25913919/b0c087c4-3579-11e7-9f90-029872b02a14.png)

**Comment by isantop** [comment]
Thanks for your message! Right now, we aren't really working on Icon Requests. However, any icons added to upstream Papirus are frequently pulled into Pop, so filing the request there is definitely the best way to go.

**Comment by SmartFinn** [comment]
@isantop already added here 52f52c9

**Comment by isantop** [comment]
@SmartFinn I think you guys win the upstream-of-the-year award! :)
