### ISSUE TITLE
System tray not replaced on Unity 7 (16.04)

### ISSUE THREAD

**Issue by HenriqueY** [system76/pop-icon-theme#5]
![captura de tela de 2017-05-24 13-27-04](https://cloud.githubusercontent.com/assets/25267506/26414243/f131d810-4084-11e7-95b4-742fcf0d0268.png)
![captura de tela de 2017-05-24 13-27-044](https://cloud.githubusercontent.com/assets/25267506/26414255/fa8e9a92-4084-11e7-89db-617bb09211f2.png)

**Comment by SmartFinn** [comment]
These icons are hardcoded, use [Hardcode-Tray](https://github.com/bil-elmoussaoui/Hardcode-Tray) to fix that.

**Comment by henriquey** [comment]
Wow, that was quick. Thanks!
It worked!

![captura de tela de 2017-0](https://cloud.githubusercontent.com/assets/25267506/26415412/c99c3ee0-4088-11e7-8eeb-99c6f78cac57.png)

**Comment by SmartFinn** [comment]
@HenriqueY there is no other way to fix it. Only Stremio devs can do this.

**Comment by bil-elmoussaoui** [comment]
@HenriqueY I can fix it if you report the issue on the correct repository ;)

**Comment by isantop** [comment]
Closing this for now.
