### ISSUE TITLE
Steam Taskbar icon broken or missing

### ISSUE THREAD

**Issue by primetoxinz** [system76/pop-icon-theme#8]
**Reporter info**

 * Arch Lunux
 * Gtk+ 3.0 version - 3.22.15-1
 * Desktop environment - Openbox 
 * Pop version - git build as of 6/1
 
 * Taskbar icon for steam looks like this - https://imgur.com/a/BOtpf,
   While applications icon looks like this - https://imgur.com/a/qRN5m

**Comment by isantop** [comment]
Many of the taskbar icons are hardcoded into the applications themselves, and they can't be fixed directly in Pop. You should have a look at [Hardcode-Tray](https://github.com/bil-elmoussaoui/Hardcode-Tray), as that can fix some hardcoded icons and does work with Pop.

**Comment by primetoxinz** [comment]
How could this possibly be hardcoded when it works on other icon themes such as Numix?

**Comment by SmartFinn** [comment]
@primetoxinz did you run [Hardcode-Tray](https://github.com/bil-elmoussaoui/Hardcode-Tray) before? Could you make a screenshot with Numix?

**Comment by primetoxinz** [comment]
I have gotten to work after a couple tries with Hardcode Tray. It worked at some point before I used Hardcode-Tray but not really worried about it now that it works.
